# Generated by Django 4.2.7 on 2025-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('prediction', models.CharField(choices=[('FAKE', 'Fake News'), ('REAL', 'Real News')], max_length=10)),
                ('confidence', models.FloatField()),
                ('probability', models.FloatField()),
                ('explanation', models.JSONField(default=dict)),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['prediction'], name='detection_n_predict_d222d0_idx'), models.Index(fields=['created_at'], name='detection_n_created_6a29b9_idx')],
            },
        ),
    ]
