# Generated by Django 4.2.7 on 2025-08-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('model_accuracy', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'System Metrics',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('CORRECT', 'Correct Prediction'), ('INCORRECT', 'Incorrect Prediction'), ('UNSURE', 'Not Sure')], max_length=20)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsanalysis',
            options={'verbose_name_plural': 'News Analyses'},
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='newsanalysis',
            index=models.Index(fields=['ip_address'], name='detection_n_ip_addr_bb9e85_idx'),
        ),
        migrations.AddIndex(
            model_name='newsanalysis',
            index=models.Index(fields=['confidence'], name='detection_n_confide_99592a_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='detection_r_rating_fd23e7_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_at'], name='detection_r_created_db6f75_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['ip_address'], name='detection_r_ip_addr_785f9d_idx'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='news_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='detection.newsanalysis'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['date'], name='detection_s_date_b67eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['feedback_type'], name='detection_u_feedbac_31c661_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['created_at'], name='detection_u_created_9239ed_idx'),
        ),
    ]
